[build]
  command = "npm run build"
  publish = ".next"

# این قسمت باعث میشه تمام route ها در Node.js runtime اجرا شن
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsonwebtoken"]
  included_files = ["app/api/**"]
